# Generated by Django 2.1.1 on 2019-08-10 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogging', '0002_remove_create_post_published_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='create_post',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
